version: '3.0'
services:
  front:
    build:
      context: ./
      dockerfile: ./.docker/Dockerfile
    container_name: react-app
    restart: always
    ports:
      - 3000:3000
    command: /usr/src/app/.docker/entrypoint.sh
    volumes:
      - ./:/usr/src/app
